apiVersion: v1
kind: Pod
metadata:
  name: app
  labels:
    name: app
spec:
  containers:
  - name: app
    image: shrade1206/todo
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    env:
      - name: A
        value: B
    command:
      - sh
    args:
      - server
    ports:
      - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: app
spec:
  selector:
    app: app
  ports:
  - port: 8080
    targetPort: 8080
