apiVersion: v1
kind: PersistentVolume
metadata:
  name: mypv
spec:
  storageClassName: todo
  capacity:
    storage: 1Gi 
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  mountOptions:
    - hard
    - nfsvers=4.1
  nfs:
    path: /SqlData
    server: 172.17.0.2
