apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mypvc
  # namespace: 
spec:
  storageClassName: todo
  resources:
    requests:
      storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
