version: "3.8"

services : 
  mysql:
    container_name: "mysql"
    image: mysql:5.7.36
    # buile:
    #   context: .
    #   dockerfile: db.Dockerfile
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_USER: root
      MYSQL_ROOT_PASSWORD: root
      # MYSQL_USER: Larry
      # MYSQL_PASSWORD: root
      MYSQL_DATABASE: todolist
    depends_on:
      - app
    command: mysqld --character-set-server=utf8 --collation-server=utf8_general_ci
    command: 
      - --default-authentication-plugin=mysql_native_password
    volumes:
      - ./mysql/initdb:/docker-entrypoint-initdb.d 
      #初始化資料表
      - ./mysql/datadir:/var/lib/mysql             
      #指定資料庫儲存位置
      - ./mysql/my.cnf:/ect/mysql/conf.d/my.cnf    
      #MySQL設定
    restart: unless-stopped
  phpmyadmin:
    container_name: pma
    image: phpmyadmin
    links:
      - mysql
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      # PMA_ARBITRARY: 1
    ports:
      - 8081:80
  app:
    container_name: "todo_list"
    image: todolist
    ports:
      - "8080:8080"
    tty: true
    restart: unless-stopped
    # build:
    #   context: .
    #   dockerfile: Dockerfile
    # restart: always
    # stop_signal: SIGINT
    # stop_grace_period: 30s
    # environment:
    #   - 'DB_PORT=3306'
    #   - 'DB_HOST=mysql'

# volumes:
#   mysql: