apiVersion: apps/v1
kind: Deployment
metadata:
  name: pma
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pma
  template:
    metadata:
      labels:
        app: pma
    spec:
      containers:
      - name: myapp
        image: phpmyadmin:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
        env:
          - name: PMA_HOST
            value: mysql
          - name: PMA_PORT
            value: "3306"
          - name: PMA_USER
            value: root
          - name: PMA_PASSWORD
            value: root
---
apiVersion: v1
kind: Service
metadata:
  name: pma-service
spec:
  type: NodePort
  selector:
    app: pma
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30900

